import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci
        officiis corporis architecto eos eveniet libero reprehenderit ullam
        delectus rerum labore ducimus qui numquam provident recusandae pariatur,
        aspernatur ad doloremque officia.
      </div>
    </div>
  );
};

export default Home;
